### PR TITLE
Fix: Ninja Repo Link

### PR DESCRIPTION
**Pull request by ax3l**
The previous link was pointing to an unrelated project.

### CODE REVIEW

**Comment by shahzebsiddiqui** [comment]
Thanks @ax3l I recall this discrepancy I'll defer this to @eugeneswalker

**Review by wspear — CHANGES_REQUESTED** [review]
Are we totally sure PRUNERS/NINJA is the wrong repo? ninja-build/ninja is a build system. PRUNERS/NINJA is part of the AID suite of tools under ECP along with Archer, ReMPI and FLiT: https://confluence.exascaleproject.org/display/STTO04/2017-June%3A+WBS+1.3.2.4+-+LLNL+Tool+Suite

**Comment by wspear** [comment]
Pruners ninja is an ECP-relevant project. The ninja build system is not. I couldn't find any E4S/ECP projects that depend on the ninja build system (based on the results of `spack find -dx | grep ninja` in an E4S environment). I believe any instances where ninja shows up in E4S instead of pruners-ninja are a result of name confusion and should be corrected. This is not the only case of a complication arising from the default spack package name differing from the product name.

**Comment by eugeneswalker** [comment]
I think the way forward here is to change `ninja` to `pruners-ninja` in the root spec list for the upcoming E4S 22.05 release. If anyone thinks this is not right let us discuss here.

**Pull request closed without merging**
