### PR TITLE
Updating E4S FACILITY DASHBOARD

### PR DESCRIPTION
**Pull request by kingxleyy**

### CODE REVIEW

**Comment by shahzebsiddiqui** [comment]
@kingxleyy see https://e4s--134.org.readthedocs.build/en/134/facility_e4s.html page it doesnt have the stat count for all the spack environment. Also please add the link for all the `spack.yaml` for math-libs, data, tools 

Screenshot 2023-08-02 at 11 41 17 AM

Screenshot 2023-08-02 at 11 40 44 AM

**Comment by kingxleyy** [comment]
when you say it doesnt have the stat count for all the spack environment, do you mean total installed specs for math-libs, data and tools?

**Comment by shahzebsiddiqui** [comment]
> e stat count for all the spack en

yes please the columns `Total Installed Specs`, `Spack.yaml`, Spack Find File. There should be total of 7 entries one per each stack.

**Comment by shahzebsiddiqui** [comment]
thanks @kingxleyy this looks good

**Comment by kingxleyy** [comment]
> thanks @kingxleyy this looks good

thank you 🙏

**Pull request merged**
